FROM python:3.8 

#RUN apt-get update 
#RUN apt-get install python3-pip
#RUN apt-get install flask

ADD app.py /
ADD requirements.txt /
ADD /templates/ /templates/

RUN pip3 install -r requirements.txt

WORKDIR /

EXPOSE 5000

CMD ["python3","app.py"]