#docker-compose file for starting up all database containers

version: "3.1"

services:
  mariadb:
    image: mariadb:10.11.2
    container_name: mariadb
    restart: always
    ports:
      - 3306:3306
    command: --max_allowed_packet=67108864
    environment:
      MYSQL_ROOT_PASSWORD: user
      MYSQL_DATABASE: mariadb
      MYSQL_USER: root
      MYSQL_PASSWORD: user

  mongo:
    image: mongo:6.0
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root

  cassandra:
    image: cassandra:4.1
    container_name: cassandra
    ports:
      - 9042:9042

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.1
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1

  postgres:
    image: postgres:15.2 #github docker library only shows latest as 15
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: user